import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import MovieDetailSummary from '.';

export default {
  title: 'Components/MovieDetailSummary',
  component: MovieDetailSummary,
  // More on argTypes: https://storybook.js.org/docs/react/api/argtypes
  argTypes: {},
} as ComponentMeta<typeof MovieDetailSummary>;

const Template: ComponentStory<typeof MovieDetailSummary> = (args) => (
  <MovieDetailSummary {...args} />
);

export const Primary = Template.bind({});
// More on args: https://storybook.js.org/docs/react/writing-stories/args
Primary.args = {
  movieDetail: {
    MakingNationNameKR: '한국',
    MakingNationNameUS: '한국',
    MakingNationName: null,
    MovieGenreCode: '20',
    PlayTime: 115,
    SoundTypeCode: '100,300',
    SoundTypeNameKR: '일반사운드,Atmos',
    SoundTypeNameUS: '일반사운드,Atmos',
    FourDTypeCode: '100,200',
    FourDTypeNameKR: '일반,Super 4D',
    FourDTypeNameUS: '일반,Super 4D',
    TranslationDivisionCode: '',
    TranslationDivisionNameKR: '',
    TranslationDivisionNameUS: '',
    HomepageURL: 'http://www.bando2020.kr',
    SynopsisKR:
      '<b> 전대미문의 재난 그 후 4년<br>폐허의 땅으로 다시 들어간다! </b><br><br>4년 전, 나라 전체를 휩쓸어버린 전대미문의 재난에서<br>가까스로 탈출했던 ‘정석’(강동원).<br>바깥세상으로부터 철저히 고립된 반도에<br>다시 들어가야 하는 피할 수 없는 제안을 받는다.<br><br>제한 시간 내에 지정된 트럭을 확보해<br>반도를 빠져 나와야 하는 미션을 수행하던 중<br>인간성을 상실한 631부대와 4년 전보다 더욱 거세진<br>대규모 좀비 무리가 정석 일행을 습격한다.<br><br>절체절명의 순간,<br>폐허가 된 땅에서 살아남은 ‘민정’(이정현) 가족의 도움으로<br>위기를 가까스로 모면하고<br>이들과 함께 반도를 탈출할 수 있는 마지막 기회를 잡기로 한다.<br><br><b> 되돌아온 자, 살아남은 자 그리고 미쳐버린 자<br>필사의 사투가 시작된다! </b>',
    SynopsisUS:
      '<b> 전대미문의 재난 그 후 4년<br>폐허의 땅으로 다시 들어간다! </b><br><br>4년 전, 나라 전체를 휩쓸어버린 전대미문의 재난에서<br>가까스로 탈출했던 ‘정석’(강동원).<br>바깥세상으로부터 철저히 고립된 반도에<br>다시 들어가야 하는 피할 수 없는 제안을 받는다.<br><br>제한 시간 내에 지정된 트럭을 확보해<br>반도를 빠져 나와야 하는 미션을 수행하던 중<br>인간성을 상실한 631부대와 4년 전보다 더욱 거세진<br>대규모 좀비 무리가 정석 일행을 습격한다.<br><br>절체절명의 순간,<br>폐허가 된 땅에서 살아남은 ‘민정’(이정현) 가족의 도움으로<br>위기를 가까스로 모면하고<br>이들과 함께 반도를 탈출할 수 있는 마지막 기회를 잡기로 한다.<br><br><b> 되돌아온 자, 살아남은 자 그리고 미쳐버린 자<br>필사의 사투가 시작된다! </b>',
    Synopsis: null,
    TotalViewCount: 44335,
    AgePrefer10: '6.3',
    AgePrefer20: '40.1',
    AgePrefer30: '27.4',
    AgePrefer40: '26.2',
    ManPrefer: '44.4',
    WomanPrefer: '55.6',
    KOFCustCnt: 1764,
    AggrDt: '2020-07-10 오전 12:00:00',
    MakingNationNameKR2: '',
    MakingNationNameKR3: '',
    MovieGenreNameKR2: '드라마',
    MovieGenreNameKR3: '',
    RepresentationMovieCode: '16010',
    MoviePlayYN: 'Y',
    MoviePlayEndYN: 0,
    MovieNameKR: '반도',
    MovieNameUS: '반도',
    MovieName: null,
    PosterURL: '/Media/MovieFile/MovieImg/202007/16010_103_1.jpg',
    ViewGradeCode: 15,
    ViewGradeNameKR: '15세이상관람가',
    ViewGradeNameUS: '15세이상관람가',
    ViewGradeName: null,
    BookingRate: 78.04,
    ReleaseDate: '2020-07-15 오전 12:00:00',
    DDay: null,
    ExpectEvaluation: 0,
    ViewEvaluation: 7.4,
    Evaluation: 0,
    BookingYN: 'Y',
    ViewRate: 78.04,
    SpecialScreenDivisionCode: [
      '200',
      '300',
      '301',
      '930',
      '941',
      '950',
      '960',
      '980',
      '986',
      '987',
    ],
    SoloOpenYN: null,
    OpenORClosing: 0,
    BookingRank: '1',
    ViewSortSequence: null,
    BookingSortSequence: null,
    FilmCode: '200',
    FilmName: '2D',
    MovieFestivalID: 0,
    DirectorName: null,
    ActorName: null,
    MovieGenreNameKR: '액션',
    MovieGenreNameUS: '액션',
    MovieGenreName: null,
    ProductionCompanyName: '(주)영화사 레드피터',
    MovieDivisionCode: null,
    MovieFestivalName: null,
    MovieFestivalFilmCount: null,
    MovieFestivalOpenDate: null,
    MovieFestivalFinalDate: null,
    MovieFestivalOpenMovieCode: null,
    MovieFestivalOpenMovieName: null,
    MovieFestivalFinalMovieCode: null,
    MovieFestivalFinalMovieName: null,
    ImagePath: null,
    ImageALT: null,
    LinkDivisionCode: null,
    ParameterEventID: null,
    ParameterRepMovieCode: null,
    URL: null,
    PopupTitle: null,
    KOFMovieCd: null,
    PlanedRelsYN: 1,
    PlanedRelsMnth: '2020-07',
    KeywordID: null,
    KeywordNm: null,
    MoreLookCD: null,
    MoreLookUrl: null,
    MoreLookImgUrl: null,
    MoreLookImgAlt: null,
    UpdateYn: null,
    ArrayStandardCd: null,
    UpdateDt: null,
    LikeYN: 'N',
    ViewCount: 0,
    LikeCount: 1040,
    TargetMovieListCode: 0,
    ViewCountSortSequence: 0,
  },
  casting: [
    {
      RepresentationMovieCode: '16010',
      StaffName: '연상호',
      StaffImage: '/Media/MovieFile/PersonImg/53000/52363_107_1.jpg',
      Role: '감독',
    },
    {
      RepresentationMovieCode: '16010',
      StaffName: '강동원',
      StaffImage: '/Media/MovieFile/PersonImg/29000/28419_107_3.png',
      Role: '배우',
    },
    {
      RepresentationMovieCode: '16010',
      StaffName: '이정현',
      StaffImage: '/Media/MovieFile/PersonImg/2000/1401_107_3.jpg',
      Role: '배우',
    },
    {
      RepresentationMovieCode: '16010',
      StaffName: '권해효',
      StaffImage: '/Media/MovieFile/PersonImg/5000/4917_107_2.jpg',
      Role: '배우',
    },
    {
      RepresentationMovieCode: '16010',
      StaffName: '김민재',
      StaffImage: '/Media/MovieFile/PersonImg/85000/84891_107_5.jpg',
      Role: '배우',
    },
  ],
};
