export type Movie = {
  RepresentationMovieCode: string;
  MoviePlayYN: string | null;
  MoviePlayEndYN: number;
  MovieNameKR: string | null;
  MovieNameUS: string | null;
  MovieName: any;
  PosterURL: string;
  ViewGradeCode: number;
  ViewGradeNameKR: string | null;
  ViewGradeNameUS: string | null;
  ViewGradeName: any;
  BookingRate: number;
  ReleaseDate: string | null;
  DDay: string | null;
  ExpectEvaluation: number;
  ViewEvaluation: number;
  Evaluation: number;
  BookingYN: string | null;
  ViewRate: number;
  SpecialScreenDivisionCode: string[] | null;
  SoloOpenYN: any;
  OpenORClosing: number;
  BookingRank: any;
  ViewSortSequence: any;
  BookingSortSequence: any;
  FilmCode: any;
  FilmName: any;
  MovieFestivalID: number;
  DirectorName: any;
  ActorName: any;
  MovieGenreNameKR: any;
  MovieGenreNameUS: any;
  MovieGenreName: any;
  ProductionCompanyName: any;
  MovieDivisionCode: string | null;
  MovieFestivalName: string | null;
  MovieFestivalFilmCount: string | null;
  MovieFestivalOpenDate: string | null;
  MovieFestivalFinalDate: string | null;
  MovieFestivalOpenMovieCode: any;
  MovieFestivalOpenMovieName: any;
  MovieFestivalFinalMovieCode: any;
  MovieFestivalFinalMovieName: any;
  ImagePath: string | null;
  ImageALT: string | null;
  LinkDivisionCode: string | null;
  ParameterEventID: string | null;
  ParameterRepMovieCode: string | null;
  URL: string | null;
  PopupTitle: string | null;
  KOFMovieCd: string | null;
  KOFCustCnt: number;
  PlanedRelsYN: number;
  PlanedRelsMnth: any;
  KeywordID: string | null;
  KeywordNm: string | null;
  MoreLookCD: string | null;
  MoreLookUrl: string | null;
  MoreLookImgUrl: string | null;
  MoreLookImgAlt: string | null;
  UpdateYn: string | null;
  ArrayStandardCd: string | null;
  UpdateDt: string | null;
  LikeYN: string | null;
  PlayTime: number;
  ViewCount: number;
  LikeCount: number;
  TargetMovieListCode: number;
  ViewCountSortSequence: number;
};

// export type Movies = {
//   Movies: {
//     Items: Array<{
//       Items: Movie[];
//       ItemCount: number;
//       KeywordID: string;
//       KeywordNm: string;
//       UpdateYn: string;
//       MoreLookCD: string;
//       MoreLookUrl: string;
//       MoreLookImgUrl: string;
//       MoreLookImgAlt: string;
//       ArrayStandardCd: string;
//       UpdateDt: string;
//       TargetMovieListCode: number;
//     }>;
//   };
//   IsOK: string;
//   ResultMessage: string;
//   ResultCode: any;
//   EventResultYn: any;
// };

// export type SpecialMovies = {
//   Movies: {
//     Items: Movie[];
//     ItemCount: number;
//     KeywordID: string | null;
//     KeywordNm: string | null;
//     UpdateYn: string | null;
//     MoreLookCD: string | null;
//     MoreLookUrl: string | null;
//     MoreLookImgUrl: string | null;
//     MoreLookImgAlt: string | null;
//     ArrayStandardCd: string | null;
//     UpdateDt: string | null;
//     TargetMovieListCode: number;
//   };
//   IsOK: string;
//   ResultMessage: string;
//   ResultCode: any;
//   EventResultYn: any;
// };
