import Carousel from '@/components/Carousel';
import Layout from '@/components/Layout';
import MovieCardList from '@/components/MovieCardList';
import { CarouselItem } from '@/types/carousel';
import { Movie } from '@/types/movie';
import { useQuery } from '@tanstack/react-query';
import axios from 'axios';
import Head from 'next/head';

export default function Home() {
  // TODO: API 호출 에러 처리 공통화
  const { data: carouselItems, isSuccess: isCaroucelSuccess } = useQuery({
    queryKey: ['carousel', { use: 'home' }],
    queryFn: async () => {
      const res = await axios.get<CarouselItem[]>('/api/carousel', { params: { use: 'home' } });
      return res.data;
    },
  });

  const { data: movies, isSuccess: isMoviesSuccess } = useQuery({
    queryKey: ['movies', { limit: 21 }],
    queryFn: async () => {
      const res = await axios.get<Movie[]>('/api/movies', { params: { limit: 21 } });
      return res.data;
    },
  });

  // TODO: 로딩 및 에러 처리 고도화
  if (!isCaroucelSuccess || !isMoviesSuccess) return <></>;

  return (
    <>
      <Head>
        <title>Chova Cinema</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout theme="dark">
        <Carousel theme="dark" height={774} items={carouselItems} />
        <section style={{ backgroundColor: '#000', padding: '32px 0' }}>
          <div className="center">
            <MovieCardList theme="dark" movies={movies} showNum={5} />
          </div>
        </section>
      </Layout>
    </>
  );
}
