import Layout from '@/components/Layout';
import Head from 'next/head';

// TODO: 상세화면은 Static Site Generation 활용
export default function MovieDetail() {
  return (
    <>
      <Head>
        <title>Detail - Chova Cinema</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="center">Movie Detail</div>
      </Layout>
    </>
  );
}
