import ComingSoon from '@/components/ComingSoon';
import Layout from '@/components/Layout';
import Head from 'next/head';
import { useRouter } from 'next/router';

// TODO: step1 SSR, step2 SSG
export default function MovieDetail() {
  const router = useRouter();
  const { id } = router.query;
  return (
    <>
      <Head>
        <title>Movie Detail - Chova Cinema</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <ComingSoon />
      </Layout>
    </>
  );
}
