import Layout from '@/components/Layout';
import Head from 'next/head';

// TODO: SSR, 페이지네이션(더보기)
export default function CurrentMovies() {
  return (
    <>
      <Head>
        <title>Current Movies - Chova Cinema</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="center">Current Movies</div>
      </Layout>
    </>
  );
}
