import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import MovieCard from '.';

const S3_BASE_URL = process.env.NEXT_PUBLIC_S3_BASE_URL;

export default {
  title: 'Components/MovieCard',
  component: MovieCard,
  // More on argTypes: https://storybook.js.org/docs/react/api/argtypes
  argTypes: {},
} as ComponentMeta<typeof MovieCard>;

const Template: ComponentStory<typeof MovieCard> = (args) => <MovieCard {...args} />;

export const Primary = Template.bind({});
// More on args: https://storybook.js.org/docs/react/writing-stories/args
Primary.args = {
  theme: 'light',
  number: 1,
  ticketingPath: '/ticketing',
  movieDetailPath: '/movies/16119',
  movie: {
    RepresentationMovieCode: '16119',
    MoviePlayYN: 'Y',
    MoviePlayEndYN: 0,
    MovieNameKR: '원 데이',
    MovieNameUS: '원 데이',
    MovieName: null,
    PosterURL: `${S3_BASE_URL}/Media/MovieFile/MovieImg/202007/16119_101_1.jpg`,
    ViewGradeCode: 15,
    ViewGradeNameKR: '15',
    ViewGradeNameUS: '15세이상관람가',
    ViewGradeName: null,
    BookingRate: 1.15,
    ReleaseDate: '2020-07-08 오전 12:00:00',
    DDay: '0',
    ExpectEvaluation: 0,
    ViewEvaluation: 8.3,
    Evaluation: 0,
    BookingYN: 'Y',
    ViewRate: 1.15,
    SpecialScreenDivisionCode: ['200', '950', '986', '987'],
    SoloOpenYN: null,
    OpenORClosing: 0,
    BookingRank: null,
    ViewSortSequence: null,
    BookingSortSequence: null,
    FilmCode: null,
    FilmName: null,
    MovieFestivalID: 0,
    DirectorName: null,
    ActorName: null,
    MovieGenreNameKR: null,
    MovieGenreNameUS: null,
    MovieGenreName: null,
    ProductionCompanyName: null,
    MovieDivisionCode: 'M',
    MovieFestivalName: '',
    MovieFestivalFilmCount: '0',
    MovieFestivalOpenDate: '1900-01-01 오전 12:00:00',
    MovieFestivalFinalDate: '1900-01-01 오전 12:00:00',
    MovieFestivalOpenMovieCode: null,
    MovieFestivalOpenMovieName: null,
    MovieFestivalFinalMovieCode: null,
    MovieFestivalFinalMovieName: null,
    ImagePath: '',
    ImageALT: '',
    LinkDivisionCode: '0',
    ParameterEventID: '',
    ParameterRepMovieCode: '',
    URL: '/NLCHS/Movie/MovieDetailView?movie=16119',
    PopupTitle: '',
    KOFMovieCd: '20112561',
    KOFCustCnt: 217513,
    PlanedRelsYN: 0,
    PlanedRelsMnth: null,
    KeywordID: '0',
    KeywordNm: '',
    MoreLookCD: '',
    MoreLookUrl: '',
    MoreLookImgUrl: '',
    MoreLookImgAlt: '',
    UpdateYn: '',
    ArrayStandardCd: '',
    UpdateDt: '2020-07-16 오전 7:15:00',
    LikeYN: 'N',
    PlayTime: 0,
    ViewCount: 0,
    LikeCount: 0,
    TargetMovieListCode: 0,
    ViewCountSortSequence: 0,
  },
};
